# Generated by Django 4.1.5 on 2023-02-01 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodbt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
