# Generated by Django 4.1.5 on 2023-02-01 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodbt', '0002_journal_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='journal',
        ),
        migrations.AddField(
            model_name='question',
            name='journal',
            field=models.ManyToManyField(blank=True, related_name='questions', to='rodbt.journal'),
        ),
    ]
