# Generated by Django 4.1.5 on 2023-02-02 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodbt', '0003_remove_question_journal_question_journal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='edited_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Edited Date'),
        ),
        migrations.AlterField(
            model_name='question',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='question',
            name='edited_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Edited Date'),
        ),
    ]
