# Generated by Django 4.1.5 on 2023-02-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodbt', '0004_alter_journal_date_alter_journal_edited_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='body',
            field=models.TextField(verbose_name='Journal Body Text'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='question',
            name='body',
            field=models.CharField(max_length=200, verbose_name='Question Body Text'),
        ),
    ]
