# Generated by Django 4.1.5 on 2023-02-14 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rodbt', '0005_alter_journal_body_alter_journal_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journals', to=settings.AUTH_USER_MODEL, verbose_name='The Big Journal!'),
        ),
    ]
